name: grouper-dev
channels:
  - conda-forge
  - pyg
  - pytorch
dependencies:
  - python>=3.9
  - boost
  - cmake
  - rdkit
  - librdkit-dev
  - librdkit
  - rdkit-dev
  - rdkit-postgresql
  - eigen
  - pybind11
  - mbuild
  - nauty
  - jupyter
  - seaborn
  - cairosvg
  - pyg
  - pytorch
  - pytest-benchmark
  - pytest
  - nlohmann_json
  - python-igraph
  - dash
  - dash_cytoscape
  - sklearn
  - pip